def get_products_db_mock() -> list:
    products = [{'id': '5601007001325', 'created_at': 'datetime.datetime(2023, 11, 25, 11, 20, 30)',
                 'updated_at': 'datetime.datetime(2023, 11, 25, 11, 20, 30)', 'name': 'Esteva',
                 'img': 'https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/202011/12/05218716000270____2__600x600.jpg',
                 'brand': 'Esteva', 'sub_brand': None, 'capacity': 375, 'harvest_year': 2021},
                {'id': '5601007002254', 'created_at': 'datetime.datetime(2023, 11, 25, 11, 18, 31)',
                 'updated_at': 'datetime.datetime(2023, 11, 25, 11, 18, 46)', 'name': 'Barca Velha Douro',
                 'img': 'https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/202210/27/05213337311255____1__1200x1200.jpg',
                 'brand': 'Casa Ferreirinha', 'sub_brand': None, 'capacity': 1500, 'harvest_year': 2011},
                {'id': '5601007476505', 'created_at': 'datetime.datetime(2023, 11, 25, 11, 44, 28)',
                 'updated_at': 'datetime.datetime(2023, 11, 25, 11, 44, 28)', 'name': 'Quinta da Leda',
                 'img': 'https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/201904/08/05218716005592____2__600x600.jpg',
                 'brand': 'Quinta da Leda', 'sub_brand': None, 'capacity': 750, 'harvest_year': 2019},
                {'id': '5601012001310', 'created_at': 'datetime.datetime(2023, 10, 24, 21, 22, 31)',
                 'updated_at': 'datetime.datetime(2023, 10, 25, 9, 13, 29)', 'name': 'Mateus Sparkling Brut Rosé',
                 'img': 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwb34c4e57/images/col/434/4342301-frente.jpg?sw=2000&sh=2000',
                 'brand': 'Mateus', 'sub_brand': None, 'capacity': 750, 'harvest_year': None},
                {'id': '5601012007497', 'created_at': 'datetime.datetime(2023, 11, 25, 11, 21, 45)',
                 'updated_at': 'datetime.datetime(2023, 11, 25, 11, 21, 45)', 'name': 'Gazela Sangria Branca',
                 'img': 'https://sgfm.elcorteingles.es/SGFM/dctm/MEDIA03/202103/18/05218718701263____1__1200x1200.jpg',
                 'brand': 'Gazela', 'sub_brand': None, 'capacity': 750, 'harvest_year': None},
                {'id': '5601012011500', 'created_at': 'datetime.datetime(2023, 10, 24, 14, 13, 7)',
                 'updated_at': 'datetime.datetime(2023, 10, 25, 9, 15, 6)', 'name': 'Mateus Rosé',
                 'img': 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwa4148cdf/images/col/205/2050174-frente.jpg?sw=2000&sh=2000',
                 'brand': 'Mateus', 'sub_brand': None, 'capacity': 750, 'harvest_year': None},
                {'id': '5601012011920', 'created_at': 'datetime.datetime(2023, 10, 24, 15, 8, 11)',
                 'updated_at': 'datetime.datetime(2023, 11, 25, 11, 41, 45)', 'name': 'Papa Figos Branco',
                 'img': 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw65f388a2/images/col/627/6274693-frente.jpg?sw=2000&sh=2000',
                 'brand': 'Casa Ferreirinha', 'sub_brand': 'Papa Figos', 'capacity': 750, 'harvest_year': 2021},
                {'id': '5601096334328', 'created_at': 'datetime.datetime(2023, 10, 25, 8, 25, 32)',
                 'updated_at': 'datetime.datetime(2023, 10, 25, 9, 15, 37)',
                 'name': 'Casal Garcia Sparkling Espumante Rosé',
                 'img': 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwff861e16/images/col/569/5694889-frente.jpg?sw=2000&sh=2000',
                 'brand': 'Casal Garcia', 'sub_brand': None, 'capacity': 750, 'harvest_year': None}]
    return products


def get_stores_db_mock() -> list:
    stores = [{'id': 1, 'created_at': 'datetime.datetime(2023, 11, 25, 12, 45, 17)',
               'updated_at': 'datetime.datetime(2023, 11, 25, 12, 45, 17)', 'name': 'Auchan',
               'search_url': 'https://www.auchan.pt/pt/pesquisa?q=',
               'logo_url': 'https://www.auchan-retail.pt/wp-content/uploads/sites/2/2020/10/logotype_RVB_HD-1024x439.png',
               'use_generic': 0, 'redirected': 0, 'currency': 'EUR',
               'x_cookies': '//button[@id="onetrust-accept-btn-handler"]',
               'x_url': '//div[@class="auc-search__right-section"]//a[@class="link"]',
               'x_name': '//h1[@class="product-name auc-hero-title"]',
               'x_price': '//div[@class="attributes"]//span[@class="value"]', 'x_year': None,
               'x_capacity': '//*[@id="collapsible-attributes-1"]/ul[1]/li', 'enabled': 0},
              {'id': 2, 'created_at': 'datetime.datetime(2024, 5, 21, 12, 55, 42)',
               'updated_at': 'datetime.datetime(2024, 5, 21, 12, 56, 19)', 'name': 'Wine44',
               'search_url': 'https://wine44.com/en/search?type=product&options%5Bprefix%5D=last&q=',
               'logo_url': 'https://wine44.com/cdn/shop/files/wine-logo.png?v=1629538780', 'use_generic': 0,
               'redirected': 0, 'currency': 'EUR', 'x_cookies': '//button[@id="submit_birthdate"]',
               'x_url': '//div[@class="new-grid search-grid"]//div[@class="grid-item__content"]//a',
               'x_name': '//h1[@class="h2 product-single__title"]/text()',
               'x_price': '//span[@class="product__price"]//span[@aria-hidden="true"]/text()', 'x_year': None,
               'x_capacity': "//span[text()[contains(., 'ml')]]/text()", 'enabled': 0},
              {'id': 3, 'created_at': 'datetime.datetime(2023, 11, 25, 17, 19, 32)',
               'updated_at': 'datetime.datetime(2023, 12, 12, 11, 58, 2)', 'name': 'Garrafinhas',
               'search_url': 'https://garrafinhas.pt/?s=',
               'logo_url': 'https://garrafinhas.pt/wp-content/uploads/2023/07/garrafinhas-logotipo.png',
               'use_generic': 0,
               'redirected': 0, 'currency': 'EUR',
               'x_cookies': '//button[@class="age-gate-submit age-gate-submit-yes"]',
               'x_url': '//a[@class="more-link button primary is-outline is-smaller"]',
               'x_name': '//h1[@class="product-title product_title entry-title"]/text()',
               'x_price': '//p[@class="price product-page-price "]//bdi/text()', 'x_year': None,
               'x_capacity': '//div[@class="custom-fields-body"]//div[text()[contains(., \'Lts.\')]]/text()',
               'enabled': 0},
              {'id': 4, 'created_at': 'datetime.datetime(2024, 5, 21, 17, 16, 8)',
               'updated_at': 'datetime.datetime(2024, 5, 21, 17, 16, 8)', 'name': 'Garrafeira Nacional',
               'search_url': 'https://www.garrafeiranacional.com/catalogsearch/result/?q=',
               'logo_url': 'https://consumertrends.pt/wp-content/uploads/2019/12/Garrafeira-vencedor-escolha-do-consumidor-2020.jpg',
               'use_generic': 0, 'redirected': 0, 'currency': 'EUR', 'x_cookies': '//button[@class="icon-ok age-ok"]',
               'x_url': '//div[@class="column main"]//div[@class="column eql "]//a[@class="product-item-link"][@href]',
               'x_name': '//span[@itemprop="name"]/text()',
               'x_price': '//div[@class="product-info-main col-md-6 col-sm-6 col-xs-12 right_column"]//span[@class="price-container price-final_price tax weee rewards_earn"]',
               'x_year': None, 'x_capacity': '//div[@class="row"]//p//a[text()[contains(., \'cl\')]]/text()',
               'enabled': 0},
              {'id': 5, 'created_at': None, 'updated_at': None, 'name': 'Asda',
               'search_url': 'https://groceries.asda.com/search/',
               'logo_url': 'https://media.timeout.com/images/106089034/750/422/image.jpg', 'use_generic': 1,
               'redirected': 0, 'currency': 'EUR', 'x_cookies': '//button[@id="onetrust-accept-btn-handler"]',
               'x_url': '//ul[@class=" co-product-list__main-cntr co-product-list__main-cntr--rest-in-shelf"]//li[@class=" co-item co-item--rest-in-shelf "]//div[@class="co-item__title-container co-item__title-container--rest-in-shelf"]//a',
               'x_name': '//h1[@class="pdp-main-details__title"]/text()',
               'x_price': '//strong[@class="co-product__price pdp-main-details__price"]/text()', 'x_year': '',
               'x_capacity': '//div[@class="pdp-main-details__weight"]/text()', 'enabled': 1}
              ]
    return stores
